DROP TABLE audio_fingerprints;

CREATE TABLE audio_fingerprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash BIGINT NOT NULL,
    track_id UUID NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    anchor_offset_ms INTEGER NOT NULL
);

CREATE INDEX idx_audio_fingerprints_hash ON audio_fingerprints(hash);
CREATE INDEX idx_audio_fingerprints_track_id ON audio_fingerprints(track_id);
